# Generated by Django 5.1.1 on 2024-12-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('purpose', models.TextField()),
                ('last_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('field_placeholder', models.TextField()),
                ('field_type', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.forms')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formfield')),
            ],
        ),
    ]
