# Generated by Django 5.1.1 on 2024-12-27 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('min_tenth_marks', models.FloatField(null=True)),
                ('min_higher_secondary_marks', models.FloatField(null=True)),
                ('min_cgpa', models.FloatField()),
                ('min_attendance', models.FloatField()),
                ('is_kt', models.BooleanField(default=False)),
                ('is_backLog', models.BooleanField(default=False)),
                ('domain', models.CharField(choices=[('core', 'core'), ('it', 'it')], max_length=40)),
                ('Departments', models.TextField(default='all')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobAcceptance',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('offer_letter', models.FileField(upload_to='')),
                ('type', models.CharField(default='', max_length=100)),
                ('salary', models.FloatField(default=0)),
                ('position', models.CharField(default='', max_length=100)),
                ('isVerified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='placement_api.companyregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_job_offer_acceptance', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='jobApplication',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('attendance', models.BooleanField(default=False)),
                ('aptitude', models.BooleanField(null=True)),
                ('gd', models.BooleanField(null=True)),
                ('case_study', models.BooleanField(null=True)),
                ('hr_round', models.BooleanField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_job_applications', to='placement_api.companyregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('position', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_offers', to='placement_api.companyregistration')),
            ],
        ),
        migrations.CreateModel(
            name='placementNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('srNo', models.TextField(default='')),
                ('to', models.TextField(default='')),
                ('subject', models.TextField(default='')),
                ('date', models.TextField(default='')),
                ('intro', models.TextField(default='')),
                ('eligibility_criteria', models.TextField(default='')),
                ('roles', models.TextField(default='')),
                ('about', models.TextField(default='')),
                ('skill_required', models.TextField(default='')),
                ('Location', models.TextField(default='')),
                ('Documents_to_Carry', models.TextField(default='')),
                ('Walk_in_interview', models.TextField(default='')),
                ('Company_registration_Link', models.TextField(default='')),
                ('Note', models.TextField(default='')),
                ('From', models.TextField(default='')),
                ('From_designation', models.TextField(default='')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_notice', to='placement_api.companyregistration')),
            ],
        ),
    ]
