# Generated by Django 5.1.1 on 2024-12-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobacceptance',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobacceptance',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobacceptance',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
