# Generated by Django 5.1.1 on 2024-12-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='batch',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='is_pli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='offers',
            field=models.ManyToManyField(blank=True, related_name='notices', to='placement_api.offers'),
        ),
    ]
