# Generated by Django 5.1.1 on 2024-12-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0003_alter_companyregistration_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_applications', to='placement_api.offers'),
        ),
    ]
