# Generated by Django 5.1.1 on 2024-12-12 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0003_alter_companyregistration_id_alter_offers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6186ce96-d899-4943-8f51-82870893dfbf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='min_higher_secondary_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companyregistration',
            name='min_tenth_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad955bb6-9ee6-44c0-bbbb-60e1d7315284'), primary_key=True, serialize=False),
        ),
    ]
