# Generated by Django 5.1.1 on 2024-12-12 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0005_alter_companyregistration_id_alter_offers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offers',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
