# Generated by Django 5.1.1 on 2024-12-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0006_alter_companyregistration_id_alter_offers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementnotice',
            name='about',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='company_registration_link',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='eligibility_criteria',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='from_designation',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='note',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='skill_required',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='placementnotice',
            name='to',
        ),
    ]
