# Generated by Django 5.1.1 on 2024-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0007_remove_placementnotice_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementnotice',
            name='Company_registration_Link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='Documents_to_Carry',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='From',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='From_designation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='Location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='Note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='Walk_in_interview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='eligibility_criteria',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='roles',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='skill_required',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='srNo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='subject',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='placementnotice',
            name='to',
            field=models.TextField(default=''),
        ),
    ]
