# Generated by Django 5.1.1 on 2024-12-12 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0008_placementnotice_company_registration_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementnotice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
