# Generated by Django 5.1.1 on 2025-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0009_jobacceptance_is_reg_jobacceptance_is_sel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='is_ojt_aedp',
            field=models.BooleanField(default=False),
        ),
    ]
