# Generated by Django 5.1.1 on 2024-12-13 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0009_alter_placementnotice_id'),
        ('student', '0010_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobacceptance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_job_offer_acceptance', to='placement_api.placementnotice'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='placement_api.placementnotice'),
        ),
        migrations.CreateModel(
            name='studentPlacementProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='student/placement_profile/pli/')),
                ('consent_pli', models.BooleanField(null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
        ),
    ]
