# Generated by Django 5.1.1 on 2024-12-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0010_alter_jobacceptance_student_and_more'),
        ('student', '0010_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobacceptance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_job_offer_acceptance', to='student.student'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_job_applications', to='placement_api.companyregistration'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
        migrations.DeleteModel(
            name='studentPlacementProfile',
        ),
    ]
