# Generated by Django 5.1.1 on 2024-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0011_alter_jobacceptance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobacceptance',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
