# Generated by Django 5.1.1 on 2024-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0012_jobacceptance_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobacceptance',
            name='offer_letter',
            field=models.FileField(upload_to=''),
        ),
    ]
