# Generated by Django 5.1.1 on 2024-12-19 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_api', '0013_alter_jobacceptance_offer_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobacceptance',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='placement_api.companyregistration'),
        ),
    ]
