<<<<<<< HEAD
# Generated by Django 5.1.1 on 2025-04-03 06:16
=======
# Generated by Django 5.1.1 on 2025-04-01 10:24
>>>>>>> 4b561beef65ed95d4a9ba1243ef6130336411ad8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0008_alter_attendancedata_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='phase',
            field=models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Phase 3', 'Phase 3')], default='Phase 1', max_length=100),
        ),
<<<<<<< HEAD
    ]
=======
    ]
>>>>>>> 4b561beef65ed95d4a9ba1243ef6130336411ad8
