# Generated by Django 5.1.1 on 2025-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_coordinator_api', '0008_alter_attendancedata_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedata',
            name='phase',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='phase',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
