export const data2024 = {
  placement_status: [
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
    "Placed",
  ],
  placement_type: [
    "PLI",
    "Normal",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "PLI",
    "Normal",
    "Normal",
    "Dream",
    "PLI",
    "PLI",
    "PLI",
    "Normal ",
    "PLI",
    "PLI",
    "PLI",
    "Dream",
    "Dream",
    "Dream",
    "Dream",
    "Normal ",
    "Normal",
    "Dream",
    "PLI",
    "Dream",
    "Normal",
    "Normal",
    "Normal",
    "Normal ",
    "PLI",
    "PLI",
    "Normal",
    "Dream",
    "Dream",
    "Super Dream",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Dream",
    "Normal",
    "Normal ",
    "PLI",
    "Normal",
    "Normal ",
    "Normal",
    "Dream",
    "Normal ",
    "Dream",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "Dream",
    "PLI",
    "Dream",
    "Normal",
    "Normal",
    "Dream",
    "Dream",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Dream",
    "Dream",
    "Dream",
    "Normal ",
    "Super Dream",
    "Dream",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Dream",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "Normal ",
    "PLI",
    "Dream",
    "PLI",
    "PLI",
    "Dream",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "Normal ",
    "Normal ",
    "Normal",
    "PLI",
    "Dream",
    "Dream",
    "Normal ",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "Dream",
    "Dream",
    "PLI",
    "Normal ",
    "Normal ",
    "Dream",
    "PLI",
    "PLI",
    "Normal/PLI",
    "Normal",
    "Dream",
    "PLI",
    "PLI",
    "Dream",
    "PLI",
    "PLI",
    "Dream",
    "PLI",
    "Dream",
    "Dream",
    "Normal",
    "Normal ",
    "Dream",
    "Normal ",
    "Normal",
    "Normal",
    "Dream",
    "PLI",
    "Normal ",
    "Normal ",
    "PLI",
    "Dream",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Dream",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "Dream",
    "PLI",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal ",
    "Normal ",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "Dream",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "Normal ",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "Normal ",
    "Normal",
    "Dream",
    "Dream",
    "Normal ",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "PLI",
    "Dream",
    "Normal ",
    "Normal",
    "Normal",
    "Normal",
    "Normal ",
    "Normal ",
    "Normal ",
    "Dream",
    "Normal",
    "Normal",
    "PLI",
    "Normal ",
    "Normal",
    "PLI",
    "Normal",
    "Normal",
    "Dream",
    "PLI",
    "Normal",
    "Normal ",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "Normal ",
    "PLI",
    "PLI",
    "Normal ",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "Normal ",
    "Normal ",
    "Normal",
    "PLI",
    "Super Dream",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "Normal ",
    "PLI",
    "PLI",
    "Normal ",
    "PLI",
    "Normal",
    "Normal ",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal ",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "Normal",
    "Normal ",
    "Dream",
    "PLI",
    "PLI",
    "PLI / Dream",
    "PLI",
    "PLI",
    "Dream",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "Normal ",
    "PLI",
    "Dream",
    "Normal",
    "Normal ",
    "Normal",
    "PLI",
    "PLI",
    "Normal ",
    "Normal ",
    "Normal ",
    "PLI",
    "Normal ",
    "Normal ",
    "PLI",
    "PLI",
    "Normal",
    "Normal ",
    "Normal ",
    "Normal ",
    "PLI",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "Normal",
    "Normal",
    "Dream",
    "Normal",
    "Normal ",
    "PLI",
    "Normal ",
    "Normal ",
    "Normal ",
    "Normal",
    "PLI",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "PLI",
    "Normal ",
    "PLI",
    "PLI",
    "PLI",
    "Normal ",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "PLI",
    "PLI",
    "PLI",
    "Normal",
    "PLI",
    "Normal ",
    "PLI",
    "PLI",
    "Normal",
    "Normal",
    "Normal",
    "Normal",
  ],
  salary_offered: [
    12.0, 4.25, 4.0, 3.0, 4.0, 4.0, 3.0, 3.6, 4.0, 8.13, 5.0, 7.5, 5.0, 3.72,
    5.0, 3.6, 3.0, 7.25, 3.6, 7.0, 5.0, 6.0, 4.5, 6.0, 3.5, 4.25, 6.5, 5.2, 3.6,
    10.0, 3.0, 4.0, 4.0, 4.0, 3.5, 3.0, 3.0, 4.0, 9.3, 40.0, 4.5, 7.0, 4.0, 3.6,
    4.05, 11.0, 4.0, 7.0, 3.6, 5.75, 3.6, 3.0, 3.5, 5.75, 3.5, 3.6, 5.75, 5.0,
    4.5, 10.2, 5.0, 5.75, 4.5, 3.5, 8.13, 4.49, 9.3, 7.0, 3.0, 3.0, 4.25, 6.0,
    4.25, 3.0, 3.0, 4.0, 3.0, 3.0, 3.0, 4.5, 3.0, 3.0, 3.0, 3.6, 3.0, 3.0, 3.25,
    3.0, 3.0, 3.25, 3.0, 3.0, 3.0, 3.25, 3.25, 3.25, 3.0, 3.0, 3.0, 3.0, 3.0,
    3.0, 3.25, 4.0, 3.0, 3.0, 3.0, 4.0, 4.0, 3.0, 3.0, 3.25, 3.0, 3.0, 4.5, 3.0,
    3.25, 3.0, 3.0, 19.75, 10.2, 8.0, 10.2, 3.0, 6.5, 12.0, 5.75, 4.5, 8.8, 3.5,
    3.0, 4.5, 4.25, 5.0, 4.06, 3.5, 5.2, 7.5, 3.2, 4.2, 8.8, 5.0, 5.2, 4.25,
    4.0, 4.5, 4.25, 7.0, 5.0, 4.5, 3.5, 4.25, 4.5, 5.0, 8.8, 7.5, 7.5, 6.18,
    4.25, 4.25, 6.18, 12.0, 8.8, 5.0, 3.5, 3.5, 10.2, 3.6, 12.0, 6.0, 3.0, 10.2,
    3.5, 11.0, 8.8, 5.2, 19.75, 8.8, 4.25, 3.5, 10.2, 4.25, 6.0, 11.0, 10.2,
    6.0, 4.5, 4.0, 19.75, 9.0, 5.2, 6.0, 4.0, 3.5, 4.5, 4.5, 4.25, 11.0, 4.0,
    4.0, 7.25, 4.25, 6.0, 4.5, 4.05, 4.0, 7.5, 7.25, 7.5, 4.5, 8.8, 8.8, 4.2,
    4.5, 3.6, 4.5, 7.5, 4.25, 4.25, 4.0, 5.2, 5.0, 8.8, 4.25, 11.0, 4.5, 5.2,
    3.6, 5.0, 4.25, 8.0, 4.0, 3.6, 3.6, 6.8, 4.0, 4.2, 4.5, 3.6, 4.5, 4.0, 4.25,
    4.25, 4.25, 3.75, 3.5, 7.5, 6.0, 5.0, 5.75, 7.0, 7.25, 3.5, 4.5, 4.0, 6.0,
    3.6, 4.25, 4.25, 6.0, 11.0, 4.5, 3.0, 4.25, 4.25, 4.0, 4.8, 4.5, 4.25, 4.25,
    3.5, 3.5, 6.18, 3.0, 6.5, 4.0, 19.75, 4.25, 4.0, 4.0, 4.25, 4.0, 3.0, 4.0,
    4.25, 4.0, 4.5, 3.5, 5.0, 3.0, 3.0, 3.5, 3.0, 3.0, 4.25, 4.0, 6.0, 4.0, 4.0,
    6.0, 3.0, 3.0, 4.0, 7.25, 3.0, 3.0, 5.0, 3.0, 4.0, 3.5, 3.0, 4.0, 3.0, 4.25,
    4.0, 4.25, 4.5, 3.0, 4.0, 5.0, 3.0, 4.5, 3.0, 3.0, 3.0, 4.0, 7.5, 6.18, 4.0,
    4.2, 11.0, 5.0, 5.75, 4.5, 4.0, 4.25, 5.0, 4.0, 5.2, 7.0, 6.0, 19.75, 3.7,
    4.25, 4.0, 5.75, 4.0, 3.6, 4.0, 4.0, 5.2, 4.5, 5.2, 5.0, 7.5, 4.25, 6.0,
    3.6, 5.2, 4.0, 3.0, 3.6, 3.0, 10.2, 9.5, 4.5, 7.5, 10.0, 8.13, 5.2, 10.17,
    6.0, 3.0, 5.0, 4.0, 4.5, 6.18, 8.8, 10.2, 8.8, 5.2, 3.5, 3.6, 4.0, 4.5, 8.0,
    5.75, 3.6, 3.25, 7.0, 5.75, 4.25, 6.0, 4.25, 3.5, 4.0, 8.8, 3.0, 5.15, 5.15,
    3.0, 3.0, 3.0, 3.0, 3.25, 3.0, 6.0, 3.25, 5.0, 3.0, 3.0, 3.6, 3.5, 3.5, 3.0,
    3.0, 4.5, 3.25, 4.0, 3.6, 3.25, 3.0, 3.05, 4.0, 4.5, 3.0, 3.0, 3.5, 4.0,
    3.0, 3.0, 6.0, 3.0, 3.6, 5.5, 3.0, 3.05, 3.0, 4.2,
  ],
  consent_status: [
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Entrepreneur",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Entrepreneur",
    "Placement",
    "Entrepreneur",
    "Entrepreneur",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Entrepreneur",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Entrepreneur",
    "Higher Studies",
    "Higher Studies",
    "Entrepreneur",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Entrepreneur",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Entrepreneur",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Entrepreneur",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Entrepreneur",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Entrepreneur",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Entrepreneur",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Entrepreneur",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Entrepreneur",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Entrepreneur",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Entrepreneur",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Higher Studies",
    "Higher Studies",
    "Placement",
    "Placement",
    "Placement",
    "Higher Studies",
    "Placement",
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ],
  categorization: [
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-2",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-2",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-1",
    "CAT-1",
    "CAT-2",
    "CAT-2",
    "CAT-2",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-1",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
    "CAT-3",
  ],
};
