# Generated by Django 5.1.1 on 2024-09-11 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=30)),
                ('academic_performance', models.FloatField()),
                ('academic_attendance', models.FloatField()),
                ('training_performance', models.FloatField()),
                ('training_attendance', models.FloatField()),
                ('current_category', models.TextField(choices=[('Category 1', 'category 1'), ('Category 2', 'category 2'), ('Category 3', 'category 3')])),
                ('is_student_coordinator', models.BooleanField(default=False)),
                ('consent', models.TextField(choices=[('placement', 'placement'), ('Higher studies', 'Higher studies')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
