# Generated by Django 5.1.1 on 2024-09-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_academic_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_performance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='training_attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='training_performance',
        ),
        migrations.AlterField(
            model_name='student',
            name='consent',
            field=models.TextField(choices=[('placement', 'placement'), ('Higher studies', 'Higher studies')], default='placement'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_category',
            field=models.TextField(choices=[('Category 1', 'category 1'), ('Category 2', 'category 2'), ('Category 3', 'category 3'), ('No category', 'No category')], default='No category'),
        ),
        migrations.CreateModel(
            name='AcademicPerformanceSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_performance', models.FloatField(default=0)),
                ('academic_attendance', models.FloatField(default=0)),
                ('semester', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_performance', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPerformanceSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_performance', models.FloatField(default=0)),
                ('training_attendance', models.FloatField(default=0)),
                ('semester', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_performance', to='student.student')),
            ],
        ),
    ]
