# Generated by Django 5.1.1 on 2024-09-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicattendancesemester',
            old_name='academic_performance',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='academicperformancesemester',
            old_name='academic_performance',
            new_name='performance',
        ),
    ]
