# Generated by Django 5.1.1 on 2024-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_trainingattendancesemester_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicattendancesemester',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], max_length=30),
        ),
        migrations.AlterField(
            model_name='academicperformancesemester',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingattendancesemester',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainingperformancesemester',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6'), ('Semester 7', 'Semester 8'), ('Semester 8', 'Semester 8')], max_length=30),
        ),
    ]
