# Generated by Django 5.1.1 on 2024-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_academicattendancesemester_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default=-4, max_length=50),
            preserve_default=False,
        ),
    ]
