# Generated by Django 5.1.1 on 2024-12-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_resume_resume_contact_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_education',
            name='end_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume_education',
            name='start_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume_project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume_workexperience',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resume_workexperience',
            name='end_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume_workexperience',
            name='start_date',
            field=models.TextField(),
        ),
    ]
