# Generated by Django 5.1.1 on 2024-12-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_resume_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_education',
            name='percentage',
            field=models.TextField(),
        ),
    ]
