# Generated by Django 5.1.1 on 2024-09-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('student', 'student'), ('system_admin', 'system_admin'), ('principal', 'principal')]),
        ),
    ]
