# Generated by Django 5.1.1 on 2024-09-29 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c59f8630-4452-4a21-a546-83e629fb97a7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
