# Generated by Django 5.1.1 on 2024-10-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('student', 'student'), ('system_admin', 'system_admin'), ('principal', 'principal'), ('department_coordinator', 'department_coordinator'), ('program_coordinator', 'program_coordinator'), ('training_officer', 'placement_officer'), ('internship_officer', 'internship_officer')]),
        ),
    ]
