# Generated by Django 5.1.1 on 2024-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_role_remove_user_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('student', 'Student'), ('system_admin', 'System Admin'), ('principal', 'Principal'), ('department_coordinator', 'Department Coordinator'), ('program_coordinator', 'Program Coordinator'), ('training_officer', 'Training Officer'), ('internship_officer', 'Internship Officer')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(related_name='users', to='base.role'),
        ),
    ]
