# Generated by Django 5.1.1 on 2024-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_role_name_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('system_admin', 'system_admin'), ('principal', 'principal'), ('department_coordinator', 'department_coordinator'), ('program_coordinator', 'program_coordinator'), ('training_officer', 'placement_officer'), ('internship_officer', 'internship_officer')], default='student', max_length=200),
        ),
    ]
