# Generated by Django 5.1.1 on 2024-10-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_secret',
            field=models.CharField(max_length=255),
        ),
    ]
