# Generated by Django 5.1.1 on 2024-10-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_passwordresetotp_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('system_admin', 'system_admin'), ('principal', 'principal'), ('department_coordinator', 'department_coordinator'), ('program_coordinator', 'program_coordinator'), ('training_officer', 'training_officer'), ('placement_officer', 'placement_officer'), ('internship_officer', 'internship_officer')], default='student', max_length=200),
        ),
    ]
